# Generated by Django 4.2.2 on 2023-06-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickersite', '0002_alter_times_dtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='dtime',
        ),
    ]
